---
# name: "Muhammad Adeeb Azim"
surname: "Muhammad Adeeb Azim Bin Mohd Nikman"
address: "Kota Bharu, Kelantan, Malaysia"
date: "`r format(Sys.time(), '%b %Y')`"
# profilepic: "./img/Adeeb.png"
phone: "(+60)143128588"
email: "adzimnikman99@gmail.com"
www: "adzim99.github.io"
linkedin: "adzim99"
headcolor: 111111
docname: Curriculum Vitae
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Experience

```{r EXPERIENCE}

experience %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    where = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    when = where
  )

```

# Education

```{r EDUCATION}

education %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    where = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    when = where
  )

```

# Projects

```{r PROJECTS}

projects %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    where = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    when = where
  )

```

# Certifications

```{r CERTIFICATIONS}

certifications %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    where = glue::glue("{Month} {Year}",.na = ""),
    when = where
  )

```

# Awards

```{r AWARDS}

awards %>%
  detailed_entries(
    with = area,
    what = unit,
    why = detail,
    where = glue::glue("{Month} {Year}",.na = ""),
    when = where
  )

```

# Skills and Languages

```{r SKILLS}

skills %>%
  detailed_entries(
    what = accomplishment,
    why = detail,
  )

```
